# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_RustDESeq2_wrappers", use_symbols = TRUE, package_name = "RustDESeq2")

#' @usage NULL
#' @useDynLib RustDESeq2, .registration = TRUE
NULL

#' @export
deseq_dataset_from_matrix <- function(count_data, nrows, ncols, gene_ids, sample_ids, condition, design_variable) .Call(wrap__deseq_dataset_from_matrix, count_data, nrows, ncols, gene_ids, sample_ids, condition, design_variable)

#' @export
deseq <- function(dds) .Call(wrap__deseq, dds)

#' @export
results <- function(dds, numerator, denominator, alpha) .Call(wrap__results, dds, numerator, denominator, alpha)

#' @export
counts <- function(dds, normalized) .Call(wrap__counts, dds, normalized)

#' @export
vst <- function(dds, blind, nsub) .Call(wrap__vst, dds, blind, nsub)

#' @export
assay <- function(vst_data) .Call(wrap__assay, vst_data)

#' @export
dispersion_estimates <- function(dds) .Call(wrap__dispersion_estimates, dds)

#' @export
dispersion_function <- function(dds) .Call(wrap__dispersion_function, dds)

#' @export
size_factors <- function(dds) .Call(wrap__size_factors, dds)

#' @export
base_mean <- function(dds) .Call(wrap__base_mean, dds)


# nolint end
