# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_RustDESeq2_wrappers", use_symbols = TRUE, package_name = "RustDESeq2")

#' @usage NULL
#' @useDynLib RustDESeq2, .registration = TRUE
NULL

#' @export
deseq_dataset_from_matrix <- function(count_data, gene_ids, sample_ids, condition, design_variable) .Call(wrap__deseq_dataset_from_matrix, count_data, gene_ids, sample_ids, condition, design_variable)

#' @export
deseq <- function(dds) .Call(wrap__deseq, dds)

#' @export
results <- function(dds, numerator, denominator, alpha) .Call(wrap__results, dds, numerator, denominator, alpha)

#' @export
counts <- function(dds, normalized) .Call(wrap__counts, dds, normalized)

#' @export
vst_transform <- function(dds, blind) .Call(wrap__vst_transform, dds, blind)

#' @export
assay <- function(obj, assay_name) .Call(wrap__assay, obj, assay_name)

#' @export
dispersions <- function(dds) .Call(wrap__dispersions, dds)

#' @export
dispersion_function <- function(dds) .Call(wrap__dispersion_function, dds)

#' @export
size_factors <- function(dds) .Call(wrap__size_factors, dds)

#' @export
base_mean <- function(dds) .Call(wrap__base_mean, dds)

#' @export
design_matrix <- function(dds) .Call(wrap__design_matrix, dds)

#' @export
coefficients <- function(dds) .Call(wrap__coefficients, dds)

#' @export
coefficient_se <- function(dds) .Call(wrap__coefficient_se, dds)


# nolint end
